# Generated by Django 5.2 on 2025-04-11 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_number', models.IntegerField(editable=False, unique=True)),
                ('incoming_date', models.DateField(default=django.utils.timezone.now)),
                ('applicant', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('responsible', models.CharField(max_length=100)),
                ('response_deadline', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
            options={
                'ordering': ['-incoming_date', '-incoming_number'],
            },
        ),
    ]
