# Generated by Django 4.2.20 on 2025-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='incoming_number',
            field=models.IntegerField(unique=True),
        ),
    ]
